# Стандартные комбинации
# Ctrl+C: копирует, если есть выделение, иначе прерывает команду (как обычно)
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

copy_on_select no
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 10000


# ---- Прозрачность ----
background_opacity 0.8
